# Generated by Django 3.2.13 on 2022-04-20 00:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('app_image', models.CharField(max_length=50)),
                ('app_video', models.CharField(max_length=50)),
                ('app_details', jsonfield.fields.JSONField()),
                ('app_download', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('app_image', models.CharField(max_length=50)),
                ('app_video', models.CharField(max_length=50)),
                ('app_details', jsonfield.fields.JSONField()),
                ('app_download', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('app_image', models.CharField(max_length=50)),
                ('app_video', models.CharField(max_length=50)),
                ('app_details', jsonfield.fields.JSONField()),
                ('app_download', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('app_image', models.CharField(max_length=50)),
                ('app_video', models.CharField(max_length=50)),
                ('app_details', jsonfield.fields.JSONField()),
                ('app_download', models.CharField(max_length=50)),
            ],
        ),
    ]
