# Generated by Django 3.2.13 on 2022-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameapp',
            name='app_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
