# Generated by Django 3.2.13 on 2022-04-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsonapp', '0002_gameapp_app_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopapp',
            name='app_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='app_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='app_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
