# Generated by Django 3.2.13 on 2022-07-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsonapp', '0003_auto_20220421_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=20)),
                ('img_dsc', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=50)),
            ],
        ),
    ]
