# Generated by Django 5.2 on 2025-04-23 18:47

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsonapp', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('project_video', models.CharField(max_length=50)),
                ('category', jsonfield.fields.JSONField()),
                ('image', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50, null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('github', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DesktopApp',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GameApp',
        ),
        migrations.DeleteModel(
            name='MobileApp',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
