# Generated by Django 5.2 on 2025-04-23 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsonapp', '0005_project_delete_desktopapp_delete_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_video',
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
    ]
