# Generated by Django 5.2 on 2025-04-24 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsonapp', '0009_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/json/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
